import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { CalendarDay, CalendarOccurrence, CalendarSource } from "../../platform/calendar";
import type { TodoOverview } from "../../platform/todo";
import type { DashboardState } from "../../types";
import { TodayWorkspace } from "./TodayWorkspace";
import { localDateKey, localDayBounds, localTomorrowKey } from "../../lib/localDate";

const mocks = vi.hoisted(() => ({ listCalendarSources: vi.fn(), listCalendarDay: vi.fn(), getTodoOverview: vi.fn(), setTodoCompleted: vi.fn(), setTodoPlannedFor: vi.fn(), getDashboard: vi.fn(), launchGroup: vi.fn(), getFocusState: vi.fn(), startFocus: vi.fn(), pauseFocus: vi.fn(), resumeFocus: vi.fn(), stopFocus: vi.fn() }));
vi.mock("../../platform/calendar", () => ({ listCalendarSources: mocks.listCalendarSources, listCalendarDay: mocks.listCalendarDay }));
vi.mock("../../platform/todo", () => ({ getTodoOverview: mocks.getTodoOverview, setTodoCompleted: mocks.setTodoCompleted, setTodoPlannedFor: mocks.setTodoPlannedFor }));
vi.mock("../../platform/dashboard", () => ({ getDashboard: mocks.getDashboard, launchGroup: mocks.launchGroup }));
vi.mock("../../platform/focus", () => ({ getFocusState: mocks.getFocusState, startFocus: mocks.startFocus, pauseFocus: mocks.pauseFocus, resumeFocus: mocks.resumeFocus, stopFocus: mocks.stopFocus }));

const source: CalendarSource = { id: "source", displayName: "work.ics", sourceType: "ics", calendarName: "工作", timezone: "Asia/Taipei", importedAt: 1, originalPath: "work.ics", fingerprint: "x" };
const event: CalendarOccurrence = { occurrenceId: "event", sourceId: source.id, sourceName: source.calendarName, uid: "event", recurrenceId: null, summary: "Project Ready", descriptionText: "", startUtc: Math.floor(Date.now() / 1000) + 3600, endUtc: Math.floor(Date.now() / 1000) + 7200, startDate: null, endDate: null, allDay: false, transparency: "opaque", status: "confirmed", recurring: false, recurrenceRule: null, lastModified: null };
const day: CalendarDay = { date: "2026-08-31", timezone: "Asia/Taipei", sources: [source], allDay: [], timed: [event], nextBlocking: event };
const dashboard: DashboardState = { pages: [], cards: [{ id: "place", pageId: "home", parentGroupId: null, cardType: "group", targetId: null, title: "Unity 學習", subtitle: "", kind: "group", symbol: "", tone: "cyan", size: "wide", position: 0, noteText: "", resumeNote: "第四節完成，接著做 Project Ready", launchEnabled: false, lastOpenedAt: "200", widgetKind: null, widgetResourceId: null }, { id: "target", pageId: "home", parentGroupId: "place", cardType: "target", targetId: "target", title: "Project Ready", subtitle: "", kind: "web", symbol: "", tone: "cyan", size: "wide", position: 1, noteText: "", resumeNote: "", launchEnabled: true, lastOpenedAt: null, widgetKind: null, widgetResourceId: null }] };
const overview: TodoOverview = { lists: [{ id: "list", title: "Unity", position: 0, createdAt: 1, updatedAt: 1, archivedAt: null }], items: [{ id: "todo", listId: "list", parentId: null, seriesId: null, title: "完成 Unity 驗收", notes: "", status: "active", priority: "high", dueAt: null, plannedFor: localDateKey(), position: 0, recurrenceKind: "none", recurrenceInterval: 1, reminderOffsetMinutes: null, reminderState: "none", createdAt: 1, updatedAt: 1, completedAt: null, deletedAt: null }] };

describe("TodayWorkspace", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.listCalendarSources.mockResolvedValue([source]); mocks.listCalendarDay.mockResolvedValue(day); mocks.getTodoOverview.mockResolvedValue(overview); mocks.setTodoCompleted.mockResolvedValue({ ...overview, items: [] }); mocks.setTodoPlannedFor.mockImplementation(async (id: string, plannedFor: string | null) => ({ ...overview, items: overview.items.map((item) => item.id === id ? { ...item, plannedFor } : item) })); mocks.getDashboard.mockResolvedValue(dashboard); mocks.launchGroup.mockResolvedValue({ items: [] }); mocks.getFocusState.mockResolvedValue({ status: "idle", phase: "focus", cycleCount: 0, startedAt: null, endsAt: null, remainingSeconds: null, linkedTodoId: null, linkedGroupId: null, updatedAt: 1, settings: { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15, longBreakInterval: 4, autoStartFocus: false, autoStartBreak: false, notificationsEnabled: true } }); });
  it("does not show calendar empty text while calendar is loading", async () => { let resolve!: (value: CalendarSource[]) => void; const pending = new Promise<CalendarSource[]>((done) => { resolve = done; }); mocks.listCalendarSources.mockReturnValueOnce(pending); render(<TodayWorkspace />); expect(screen.queryByText("今天沒有固定行程")).not.toBeInTheDocument(); resolve([]); await waitFor(() => expect(screen.queryByText("今天沒有固定行程")).not.toBeInTheDocument()); });
  it("does not show todo empty text while todo is loading", async () => { let resolve!: (value: TodoOverview) => void; const pending = new Promise<TodoOverview>((done) => { resolve = done; }); mocks.getTodoOverview.mockReturnValueOnce(pending); render(<TodayWorkspace />); expect(screen.queryByText("今天還沒安排")).not.toBeInTheDocument(); resolve({ lists: [], items: [] }); expect(await screen.findByText("今天還沒安排")).toBeInTheDocument(); });
  it("does not show continue empty text while dashboard is loading", async () => { let resolve!: (value: DashboardState) => void; const pending = new Promise<DashboardState>((done) => { resolve = done; }); mocks.getDashboard.mockReturnValueOnce(pending); render(<TodayWorkspace />); expect(screen.queryByText("還沒有最近進度")).not.toBeInTheDocument(); resolve({ pages: [], cards: [] }); await waitFor(() => expect(screen.queryByRole("heading", { name: "繼續" })).not.toBeInTheDocument()); });
  it("shows the next blocking event, todo and recent place", async () => { render(<TodayWorkspace />); expect(await screen.findByText("Project Ready")).toBeInTheDocument(); expect(screen.getByText("完成 Unity 驗收")).toBeInTheDocument(); expect(screen.getByText("Unity 學習")).toBeInTheDocument(); });
  it("gracefully omits the calendar constraint without a calendar source", async () => { mocks.listCalendarSources.mockResolvedValue([]); render(<TodayWorkspace />); await waitFor(() => expect(screen.queryByText("今天沒有固定行程")).not.toBeInTheDocument()); expect(screen.getByText("完成 Unity 驗收")).toBeInTheDocument(); });
  it("shows every explicitly planned todo and completes one", async () => { const items = Array.from({ length: 6 }, (_, index) => ({ ...overview.items[0], id: `todo-${index}`, title: `待辦 ${index}` })); mocks.getTodoOverview.mockResolvedValue({ ...overview, items }); const user = userEvent.setup(); render(<TodayWorkspace />); expect((await screen.findAllByRole("checkbox")).length).toBe(6); await user.click(screen.getAllByRole("checkbox")[0]); await waitFor(() => expect(mocks.setTodoCompleted).toHaveBeenCalledWith("todo-0", true)); });
  it("does not automatically show unplanned or tomorrow-planned todos", async () => { mocks.getTodoOverview.mockResolvedValue({ ...overview, items: [{ ...overview.items[0], plannedFor: null, title: "未安排" }, { ...overview.items[0], id: "tomorrow", plannedFor: localTomorrowKey(), title: "明天安排" }] }); render(<TodayWorkspace />); expect(await screen.findByText("今天還沒安排")).toBeInTheDocument(); expect(screen.queryByText("未安排")).not.toBeInTheDocument(); expect(screen.queryByText("明天安排")).not.toBeInTheDocument(); });
  it("collapses attention and expands due items into Today", async () => { const due = { ...overview.items[0], id: "due", title: "今天截止", plannedFor: null, dueAt: localDayBounds().start + 3600 }; const dueOverview = { ...overview, items: [due] }; mocks.getTodoOverview.mockResolvedValue(dueOverview); mocks.setTodoPlannedFor.mockResolvedValue({ ...dueOverview, items: [{ ...due, plannedFor: localDateKey() }] }); const user = userEvent.setup(); render(<TodayWorkspace />); const attention = (await screen.findByRole("heading", { name: "需要留意" })).closest("section")!; const view = within(attention).getByRole("button", { name: "查看" }); expect(view).toHaveAttribute("aria-expanded", "false"); await user.click(view); expect(view).toHaveAttribute("aria-expanded", "true"); await user.click(within(attention).getByRole("button", { name: "排到今天" })); expect(mocks.setTodoPlannedFor).toHaveBeenCalledWith("due", localDateKey()); });
  it("shows overdue attention without duplicating planned overdue items", async () => { const overdue = { ...overview.items[0], id: "overdue", title: "尚未安排的逾期", plannedFor: null, dueAt: localDayBounds().start - 60 }; const plannedOverdue = { ...overview.items[0], id: "planned-overdue", title: "已安排的逾期", dueAt: localDayBounds().start - 60 }; mocks.getTodoOverview.mockResolvedValue({ ...overview, items: [overdue, plannedOverdue] }); const user = userEvent.setup(); render(<TodayWorkspace />); const plannedSection = (await screen.findByRole("heading", { name: "今天安排" })).closest("section")!; expect(within(plannedSection).getByText("已安排的逾期")).toBeInTheDocument(); const attention = screen.getByRole("heading", { name: "需要留意" }).closest("section")!; expect(within(attention).getByText(/逾期 1/)).toBeInTheDocument(); await user.click(within(attention).getByRole("button", { name: "查看" })); expect(within(attention).getByText("尚未安排的逾期")).toBeInTheDocument(); expect(within(attention).queryByText("已安排的逾期")).not.toBeInTheDocument(); });
  it("removes planning without completing or stopping linked Focus", async () => { const user = userEvent.setup(); mocks.getFocusState.mockResolvedValue({ ...(await mocks.getFocusState()), status: "running", linkedTodoId: "todo", endsAt: Math.floor(Date.now() / 1000) + 120 }); mocks.setTodoPlannedFor.mockResolvedValue({ ...overview, items: [{ ...overview.items[0], plannedFor: null }] }); render(<TodayWorkspace />); await user.click(await screen.findByRole("button", { name: "移出今天" })); expect(mocks.setTodoPlannedFor).toHaveBeenCalledWith("todo", null); expect(mocks.setTodoCompleted).not.toHaveBeenCalled(); expect(mocks.stopFocus).not.toHaveBeenCalled(); });
  it("keeps other Today domains usable when planning fails", async () => { const user = userEvent.setup(); mocks.setTodoPlannedFor.mockRejectedValue(new Error("fail")); render(<TodayWorkspace />); await user.click(await screen.findByRole("button", { name: "移出今天" })); expect(await screen.findByRole("alert")).toHaveTextContent("安排日期無法更新"); expect(screen.getByText("完成 Unity 驗收")).toBeInTheDocument(); expect(screen.getByText("Project Ready")).toBeInTheDocument(); expect(screen.getByText("Unity 學習")).toBeInTheDocument(); });
  it("opens the continuation Place without launching it", async () => { const user = userEvent.setup(); const onOpenPlace = vi.fn(); render(<TodayWorkspace focusState={null} focusReady={true} focusError={null} onStartFocus={vi.fn(async () => undefined)} onOpenPlace={onOpenPlace} />); await user.click(await screen.findByRole("button", { name: "接著做" })); expect(onOpenPlace).toHaveBeenCalledWith("place"); expect(mocks.launchGroup).not.toHaveBeenCalled(); });
  it("keeps continuation information when no child is launchable", async () => { mocks.getDashboard.mockResolvedValue({ pages: [], cards: dashboard.cards.map((card) => card.cardType === "target" ? { ...card, launchEnabled: false } : card) }); render(<TodayWorkspace />); expect(await screen.findByText("Unity 學習")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "接著做" })).toBeInTheDocument(); });
  it("keeps calendar visible when todo loading fails", async () => { mocks.getTodoOverview.mockRejectedValue(new Error("todo")); render(<TodayWorkspace />); expect(await screen.findByText("Project Ready")).toBeInTheDocument(); expect(await screen.findByText("待辦暫時無法讀取")).toBeInTheDocument(); });
  it("keeps todo visible when calendar loading fails", async () => { mocks.listCalendarSources.mockRejectedValue(new Error("calendar")); render(<TodayWorkspace />); expect(await screen.findByText("行程暫時無法讀取")).toBeInTheDocument(); expect(await screen.findByText("完成 Unity 驗收")).toBeInTheDocument(); });
  it("omits the continue section when there is no resumable place", async () => { mocks.getDashboard.mockResolvedValue({ pages: [], cards: [] }); render(<TodayWorkspace />); await waitFor(() => expect(screen.queryByRole("heading", { name: "繼續" })).not.toBeInTheDocument()); });
  it("starts Todo focus and renders the linked context", async () => { const user = userEvent.setup(); const running = { ...(await mocks.getFocusState()), status: "running", linkedTodoId: "todo", endsAt: Math.floor(Date.now() / 1000) + 120 }; mocks.startFocus.mockResolvedValue(running); render(<TodayWorkspace />); await user.click((await screen.findAllByRole("button", { name: "開始" }))[0]); expect(mocks.startFocus).toHaveBeenCalledWith({ phase: "focus", linkedTodoId: "todo", linkedGroupId: null }); expect(await screen.findByRole("heading", { name: "正在做" })).toBeInTheDocument(); expect(screen.getAllByText("完成 Unity 驗收").length).toBeGreaterThanOrEqual(2); });
  it("does not start or launch a Place from the continuation action", async () => { const user = userEvent.setup(); const onOpenPlace = vi.fn(); render(<TodayWorkspace focusState={null} focusReady={true} focusError={null} onStartFocus={vi.fn(async () => undefined)} onOpenPlace={onOpenPlace} />); await user.click(await screen.findByRole("button", { name: "接著做" })); expect(onOpenPlace).toHaveBeenCalledWith("place"); expect(mocks.startFocus).not.toHaveBeenCalled(); expect(mocks.launchGroup).not.toHaveBeenCalled(); });
  it("shows active Focus as a return-to-focus handoff", async () => { const base = await mocks.getFocusState(); mocks.getFocusState.mockResolvedValue({ ...base, status: "paused", linkedTodoId: "todo", remainingSeconds: 100 }); render(<TodayWorkspace focusState={{ ...base, status: "paused", linkedTodoId: "todo", remainingSeconds: 100 }} focusReady={true} focusError={null} onStartFocus={vi.fn(async () => undefined)} onReturnToFocus={vi.fn()} />); expect(await screen.findByRole("button", { name: "回到專注" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "繼續" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "結束" })).not.toBeInTheDocument(); });
  it("shows generic context when a linked entity is missing", async () => { const base = await mocks.getFocusState(); mocks.getFocusState.mockResolvedValue({ ...base, status: "paused", linkedTodoId: "missing", remainingSeconds: 42 }); render(<TodayWorkspace />); expect(await screen.findByText("未連結的專注")).toBeInTheDocument(); });
  it("isolates Focus read failures", async () => { mocks.getFocusState.mockRejectedValue(new Error("focus")); render(<TodayWorkspace />); expect(await screen.findByText("正在做暫時無法讀取")).toBeInTheDocument(); expect(await screen.findByText("完成 Unity 驗收")).toBeInTheDocument(); expect(screen.getByText("Unity 學習")).toBeInTheDocument(); });
});
