import { useCallback, useEffect, useMemo, useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { importCalendarIcs, listCalendarDay, listCalendarSources, type CalendarDay, type CalendarOccurrence, type CalendarSource } from "../../platform/calendar";
import { platformErrorMessage } from "../../platform/system";

const locale = "zh-TW";
function localDateKey(date = new Date()): string { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function moveDate(dateKey: string, days: number): string { const [year, month, day] = dateKey.split("-").map(Number); return localDateKey(new Date(year, month - 1, day + days)); }
function dateLabel(dateKey: string): string { const [year, month, day] = dateKey.split("-").map(Number); return new Intl.DateTimeFormat(locale, { year: "numeric", month: "long", day: "numeric", weekday: "short" }).format(new Date(year, month - 1, day)); }
function timeLabel(timestamp: number | null): string { return timestamp === null ? "" : new Intl.DateTimeFormat(locale, { hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(timestamp * 1000)); }
function eventRange(event: CalendarOccurrence): string { return event.allDay ? "全天" : `${timeLabel(event.startUtc)}–${timeLabel(event.endUtc)}`; }
function eventDateLabel(event: CalendarOccurrence): string { if (event.allDay && event.startDate) return dateLabel(event.startDate); if (event.startUtc === null) return "日期未提供"; return new Intl.DateTimeFormat(locale, { year: "numeric", month: "long", day: "numeric", weekday: "short" }).format(new Date(event.startUtc * 1000)); }
function importedLabel(timestamp: number): string { return new Intl.DateTimeFormat(locale, { year: "numeric", month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(timestamp * 1000)); }
function durationLabel(event: CalendarOccurrence): string { if (event.allDay || event.startUtc === null || event.endUtc === null) return "全天"; const minutes = Math.max(0, Math.round((event.endUtc - event.startUtc) / 60)); const hours = Math.floor(minutes / 60); const remainder = minutes % 60; if (hours === 0) return `${minutes} 分鐘`; return remainder === 0 ? `${hours} 小時` : `${hours} 小時 ${remainder} 分鐘`; }
function busyLabel(event: CalendarOccurrence): string { return event.transparency === "transparent" ? "○ 不占用時間" : "● 占用時間"; }

function EventRow({ event, onOpen, showSource }: { event: CalendarOccurrence; onOpen: (event: CalendarOccurrence) => void; showSource: boolean }) {
  const metadata = [showSource ? event.sourceName : "", event.recurring ? "重複事件" : ""].filter(Boolean).join(" · ");
  return <li><button type="button" className="calendar-event-row" onClick={() => onOpen(event)}><span className="calendar-event-time">{eventRange(event)}</span><span className="calendar-event-copy"><strong>{event.summary || "（無標題）"}</strong>{metadata && <small>{metadata}</small>}</span><span className={`calendar-busy ${event.transparency === "transparent" ? "is-free" : ""}`}>{busyLabel(event)}</span></button></li>;
}

function EventDetail({ event, onClose }: { event: CalendarOccurrence; onClose: () => void }) {
  return <div className="calendar-detail-backdrop" role="presentation" onMouseDown={(mouseEvent) => { if (mouseEvent.target === mouseEvent.currentTarget) onClose(); }}><section className="calendar-detail" role="dialog" aria-modal="true" aria-labelledby="calendar-detail-title"><header><h2 id="calendar-detail-title">{event.summary || "（無標題）"}</h2><button type="button" className="icon-button" aria-label="關閉事件詳細資訊" onClick={onClose}>×</button></header><dl><div><dt>日期</dt><dd>{eventDateLabel(event)}</dd></div><div><dt>時間</dt><dd>{eventRange(event)} · {durationLabel(event)}</dd></div><div><dt>狀態</dt><dd>{busyLabel(event)}</dd></div><div className="calendar-detail-secondary"><dt>來源</dt><dd>{event.sourceName}</dd></div>{event.recurring && <div className="calendar-detail-secondary"><dt>重複</dt><dd>是</dd></div>}{event.lastModified !== null && <div className="calendar-detail-secondary"><dt>最後修改</dt><dd>{new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.lastModified * 1000))}</dd></div>}</dl><div className="calendar-description"><h3>描述</h3><p>{event.descriptionText || "沒有描述。"}</p></div></section></div>;
}

export function CalendarSourceManagement({ onChanged }: { onChanged?: () => void }) {
  const [sources, setSources] = useState<CalendarSource[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setSources(await listCalendarSources()); } catch (loadError) { setError(platformErrorMessage(loadError, "無法讀取行事曆來源。")); } }, []);
  useEffect(() => { void load(); }, [load]);
  const chooseAndImport = useCallback(async (sourceId?: string) => { const selected = await open({ multiple: false, filters: [{ name: "iCalendar", extensions: ["ics"] }] }); if (!selected || Array.isArray(selected)) return; setBusy(true); setError(null); try { await importCalendarIcs(selected, sourceId); await load(); onChanged?.(); } catch (importError) { setError(platformErrorMessage(importError, "無法匯入 ICS。原有行事曆資料未變更。")); } finally { setBusy(false); } }, [load, onChanged]);
  return <section className="calendar-settings" aria-labelledby="calendar-settings-title"><h3 id="calendar-settings-title">行事曆</h3><p className="settings-section-description">管理已匯入的本機行事曆來源。</p>{error && <div className="calendar-message is-error" role="alert">{error}</div>}{sources.length === 0 ? <p className="calendar-settings-empty">尚未匯入行事曆。</p> : <div className="calendar-settings-sources">{sources.map((source) => <div key={source.id}><span><strong>{source.calendarName}</strong><small>{source.displayName} · {source.timezone}<br />最後匯入：{importedLabel(source.importedAt)}</small></span><button type="button" disabled={busy} onClick={() => void chooseAndImport(source.id)}>重新匯入</button></div>)}</div>}<button type="button" className="secondary-button calendar-settings-import" disabled={busy} onClick={() => void chooseAndImport()}>{busy ? "正在匯入…" : "＋ 匯入 ICS"}</button></section>;
}

export function CalendarWorkspace() {
  const [date, setDate] = useState(() => localDateKey()); const [sources, setSources] = useState<CalendarSource[]>([]); const [day, setDay] = useState<CalendarDay | null>(null); const [selectedEvent, setSelectedEvent] = useState<CalendarOccurrence | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const timezone = useMemo(() => Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", []); const today = localDateKey(); const isToday = date === today;
  const load = useCallback(async () => { setLoading(true); setError(null); try { const nextSources = await listCalendarSources(); setSources(nextSources); setDay(nextSources.length === 0 ? null : await listCalendarDay(date, timezone)); } catch (loadError) { setError(platformErrorMessage(loadError, "無法讀取行事曆。")); } finally { setLoading(false); } }, [date, timezone]);
  useEffect(() => { void load(); }, [load]);
  const chooseAndImport = useCallback(async () => { const selected = await open({ multiple: false, filters: [{ name: "iCalendar", extensions: ["ics"] }] }); if (!selected || Array.isArray(selected)) return; setBusy(true); setError(null); setNotice(null); try { const result = await importCalendarIcs(selected); setNotice(`已匯入 ${result.importedEventCount} 個事件；${result.recurrenceCount} 個重複規則、${result.overrideCount} 個例外。`); await load(); } catch (importError) { setError(platformErrorMessage(importError, "無法匯入 ICS。原有行事曆資料未變更。")); } finally { setBusy(false); } }, [load]);
  const showSource = sources.length > 1;
  return <main className="calendar-workspace"><header className="calendar-heading"><div><h1>行事曆</h1><p>本機匯入的行程，依日期整理成可行動的 agenda。</p></div></header>{error && <div className="calendar-message is-error" role="alert">{error}</div>}{notice && <div className="calendar-message" role="status">{notice}</div>}{loading ? <div className="calendar-state" role="status">正在整理行事曆…</div> : sources.length === 0 ? <section className="calendar-empty"><span aria-hidden="true">▦</span><h2>還沒有行事曆</h2><p>匯入 .ics 後，Personal Place 會在本機整理你的時間與事件。</p><button type="button" className="primary-button" disabled={busy} onClick={() => void chooseAndImport()}>{busy ? "正在匯入…" : "選擇 ICS 檔案"}</button></section> : <><nav className="calendar-date-nav" aria-label="日期導覽"><button type="button" aria-label="前一天" onClick={() => setDate((value) => moveDate(value, -1))}>‹</button><strong>{dateLabel(date)}</strong><button type="button" aria-label="後一天" onClick={() => setDate((value) => moveDate(value, 1))}>›</button><button type="button" className="calendar-today-button" onClick={() => setDate(today)}>今天</button></nav>{isToday && day?.nextBlocking && <section className="calendar-next" aria-labelledby="calendar-next-title"><div><h2 id="calendar-next-title">下一個行程</h2><strong>{day.nextBlocking.summary}</strong><span>{eventRange(day.nextBlocking)}{showSource ? ` · ${day.nextBlocking.sourceName}` : ""}</span></div><button type="button" onClick={() => setSelectedEvent(day.nextBlocking)}>查看</button></section>}<div className="calendar-agenda">{day && day.allDay.length > 0 && <section aria-labelledby="calendar-all-day-title"><header><h2 id="calendar-all-day-title">全天</h2><span>{day.allDay.length}</span></header><ol>{day.allDay.map((event) => <EventRow key={event.occurrenceId} event={event} onOpen={setSelectedEvent} showSource={showSource} />)}</ol></section>}<section aria-labelledby="calendar-timed-title"><header><h2 id="calendar-timed-title">時間表</h2><span>{day?.timed.length ?? 0}</span></header>{!day || day.timed.length === 0 ? <p className="calendar-none">這一天沒有排定事件。</p> : <ol>{day.timed.map((event) => <EventRow key={event.occurrenceId} event={event} onOpen={setSelectedEvent} showSource={showSource} />)}</ol>}</section></div></>}{selectedEvent && <EventDetail event={selectedEvent} onClose={() => setSelectedEvent(null)} />}</main>;
}
